export const SailorsList  = [{
    id:1,
    name: "Bunny Tsukino",
    sailor: "Moon",
    sailorName:"Sailor Moon",
    description:"La primera misión de Sailor Moon es encontrar a la princesa de la Luna y a las otras Sailors Scouts a la vez que detiene al Negaverso de cumplir sus malvados planes. Para facilitar su trabajo, Luna también le da una pluma mágica con la cual se puede disfrazar de cualquier persona. En sus primeras batallas contra el Negaverso a Sailor Moon le costaba muchísimo trabajo tener que luchar por la justicia; ante los ataques de las malignas no hacía más que llorar hasta que aparecía Tuxedo Mask y le ayudaba en la batalla",
    power: "Poder de la Luna",
    photo: "https://pbs.twimg.com/profile_images/1096170522419843078/hLO_9T6j_400x400.jpg",
    outfit1:"https://c.tenor.com/GELFkdAJ2KcAAAAC/sailor-moon-transformation.gif",
    outfit2:"https://i.pinimg.com/originals/b5/d1/cd/b5d1cd7822305b0721c54224dc810ffe.jpg",
  },
  {id:2,
    name: "Ami Mizuno",
    sailor: "Mercurio",
    sailorName:"Sailor Mercury",
    description:"Como la reencarnación de una de las guerreras del Milenio de Plata, Ami empieza a manifestar los poderes que tenía en su vida pasada cuando es atacada por una maligna en la escuela. Por suerte estaban Serena y Luna, la cual se dio cuenta de que ella era Sailor Mercury; desde ese momento su vida nunca seria igual.",
    power: "Agua",
    photo:"https://i.pinimg.com/originals/08/71/61/0871610bbb9e6858dcf3ffa83afde7e3.jpg",
    outfit1:"https://c.tenor.com/P3CPyqWmSM0AAAAd/sailor-moon-sailor-mercury.gif",
    outfit2:"https://i.pinimg.com/originals/dd/c6/30/ddc630afa8625347ad0a52170639a9b1.png",
  },
  {id:3,
    name: "Rei Hino",
    sailor: "Marte",
    sailorName:"Sailor Mars",
    description:"Como el resto de las protagonistas, Rei es la reencarnación de una de las ocho guerreras que vivieron para proteger este reino en su vida pasada. En esos tiempos, cada planeta del Sistema Solar poseía una guerrera Sailor Senshi que lo protegía, y todas estas guerreras se unían para proteger en conjunto a todo el Sistema Solar.",
    power: "Fuego",
    photo:"https://64.media.tumblr.com/c13df57b92466d7c1beeb19497475c75/tumblr_pz9noz9FcR1ywnugzo4_400.png",
    outfit1:"https://pa1.narvii.com/6615/09b33a4e2d1cf62ac9582419f14c17b3826c7011_hq.gif",
    outfit2:"https://i.pinimg.com/originals/b4/91/5f/b4915fd9fea1ec9ada76a1a085ff6615.png",
  },
  {id:4,
    name: "Makoto Kino ",
    sailor: "Jupiter",
    sailorName:"Sailor Jupiter",
    description:"Como el resto de las protagonistas, Makoto/Lita es la reencarnación de una de las ocho guerreras que vivieron para proteger este reino en su vida pasada. En esos tiempos, cada planeta del Sistema Solar poseía una Sailor Scout que lo protegía, y todas estas guerreras se unían para proteger en conjunto a todo el Sistema Solar. A su vez, las guerreras se subordinaban a la autoridad de la dinastía real del Milenio de Plata, es decir la familia real de la Luna, quienes eran los guardianes más abnegados y poderosos de todo el Sistema. En su vida anterior como Sailor Jupiter, Lita vivía en el Milenio de Plata junto a sus compañeras, las otras guerreras. Una vez que este reino destruido, todas renacieron en la Tierra del siglo XX junto con Serenity, la princesa del Milenio de Plata, y su corte.",
    power: "Tormenta",
    photo:"https://i.pinimg.com/550x/bb/d8/e6/bbd8e659e518e9271403ede0577b278b.jpg",
    outfit1:"https://i.pinimg.com/originals/46/0e/75/460e75011febca9bfb0477f2f4fe0fd6.gif",
    outfit2:"https://i.pinimg.com/originals/7b/3a/7c/7b3a7c1ae7f02a4871b2a6fa55477e93.png",
  },
  {id:5,
    name: "Minako Aino",
    sailor: "Venus",
    sailorName:"Sailor Venus",
    description:"Venus es la primera Sailor Senshi encontrada por uno de los gatos lunares, un año antes que a Sailor Moon, pero es la última Senshi en aparecer en la primera temporada del anime. Trabaja sola durante unos meses como Sailor V, tratando de engañar al Negaverso, haciéndoles creer que ella era la princesa, mientras que buscaba a la verdadera. En el Milenio de Plata, fue la líder de las Sailor Internas. Conoció a Artemis con 13 años. Es la única que Tiene una serie independiente.",
    power: "Luz",
    photo:"https://www.okchicas.com/wp-content/uploads/2019/10/Moda-Sailor-Moon-6.jpg",
    outfit1:"https://c.tenor.com/YiGHpJmnrV8AAAAC/sailor-moon-sailor-venus.gif",
    outfit2:"https://i.pinimg.com/564x/5a/d5/a9/5ad5a92c96d8babaf0c4dfb7cf404f62.jpg",
  },
  {id:6,
    name: "Chibiusa",
    sailor: "Chibi-moon",
    sailorName:"Sailor Chibi-moon",
    description:"Pocos datos se tienen sobre Chibiusa en el anime antes del ataque de Black Moon, ya que lo único que se sabe es el hecho de que ella comparte la misma fecha de cumpleaños que su madre (30 de junio) y que además nació justo antes de la formación del segundo Milenio de Plata. Ella es la única princesa heredera al trono de sus padres una vez formado el segundo imperio lunar. Antes de llegar al siglo XX ella era muy exigente, como se muestra en el episodio 75 en su mente, ya que exigía que todos la llamasen Pequeña Dama como respeto, además de que no conocía los nombres de sus padres antes de convertirse en el Rey Endymion y la Neo-Reina Serenity. Su madre, la Neo-Reina Serenity en su juventud, por esta razón cuando ella viaja al pasado, se presenta de este modo ante su futura madre, que por aquella época es aún una adolescente. Ante esto, Serena comienza a llamarla Chibi-Usagi. Cuando Chibiusa se queda a vivir en la casa de su futura madre, adopta el apellido Tsukino de ella.",
    power: "Controla el cristal de plata",
    photo:"https://i.pinimg.com/474x/04/71/6b/04716be76f26c7856793f2ef272c9696.jpg",
    outfit1:"https://64.media.tumblr.com/2cd1ce281eed7c310c72e8bc51139cd3/tumblr_p55211Ix9E1vgzd4so6_500.gifv",
    outfit2:"https://i0.wp.com/codigoespagueti.com/wp-content/uploads/2020/12/maxresdefault-3.jpg?fit=1280%2C720&quality=80&ssl=1",
  },
  
]